services:
  - type: web
    name: oi-creener-bot
    env: node
    region: frankfurt
    plan: free
    branch: v2
    buildCommand: npm install --build-from-source && npm run build
    startCommand: npm run start